const STORAGE_KEY = 'safaisathi-reports-v1';
// Demo-only credentials. Move authentication to a trusted backend before deployment.
const ADMIN_LOGIN_ID = 'admin';
const ADMIN_PASSWORD = 'safai123';
const statuses = ['Reported', 'Assigned', 'In Progress', 'Resolved', 'Verified'];
const workers = [{id:'W-101',name:'Ramesh Kumar',pin:'1234'},{id:'W-102',name:'Asha Devi',pin:'2345'},{id:'W-103',name:'Imran Ali',pin:'3456'}];
const seedReports = [
  {id:'SS-024',title:'Overflowing bins near the park',name:'Riya S.',location:'Green Park, Block C',type:'Household waste',description:'The bins by the park entrance have been overflowing since yesterday evening.',priority:'High',status:'Reported',date:Date.now()-1000*60*60*3,upvotes:12,art:'bins',assignedTo:'',payAmount:0,paymentStatus:'Unpaid'},
  {id:'SS-023',title:'Plastic waste along the canal',name:'Arjun M.',location:'Riverside Walk, East Gate',type:'Plastic waste',description:'Plastic bottles and wrappers are collecting along the footpath and water edge.',priority:'Medium',status:'In Progress',date:Date.now()-1000*60*60*28,upvotes:8,art:'canal',assignedTo:'W-101',payAmount:500,paymentStatus:'Unpaid'},
  {id:'SS-022',title:'Food waste left at bus stop',name:'Meera K.',location:'Lake Road Bus Stop',type:'Food waste',description:'A pile of food scraps has been left near the shelter. It is attracting stray animals.',priority:'Low',status:'Resolved',date:Date.now()-1000*60*60*72,upvotes:5,art:'street',assignedTo:'W-102',payAmount:350,paymentStatus:'Paid'}
];
let reports = loadReports();
let activeFilter = 'all';
let toastTimer;
let currentNearbyPlaces = [];
let nearbyLookupPromise = Promise.resolve([]);
let workerWatchId = null;
const WORKER_LOCATIONS_KEY = 'safaisathi-worker-locations-v1';
function loadReports(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));return Array.isArray(saved)?saved:seedReports}catch{return seedReports}}
function saveReports(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(reports))}catch{showToast('Storage is full. Try a smaller photo.')}}
function escapeHTML(value=''){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function slug(status){return status==='In Progress'?'progress':status.toLowerCase()}
function formatDate(value){const d=new Date(value);if(Date.now()-d.getTime()<86400000)return 'Today, '+d.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});return d.toLocaleDateString([],{day:'numeric',month:'short'})}
function timeAgo(value){const hours=Math.max(0,Math.floor((Date.now()-value)/3600000));if(hours<1)return 'Just now';if(hours<24)return `${hours} hour${hours===1?'':'s'} ago`;const days=Math.floor(hours/24);return `${days} day${days===1?'':'s'} ago`}
function distanceMeters(a,b){const rad=x=>x*Math.PI/180,R=6371000,dLat=rad(b.latitude-a.latitude),dLon=rad(b.longitude-a.longitude),x=Math.sin(dLat/2)**2+Math.cos(rad(a.latitude))*Math.cos(rad(b.latitude))*Math.sin(dLon/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function samePlace(a,b){if(a.latitude!=null&&a.longitude!=null&&b.latitude!=null&&b.longitude!=null)return distanceMeters(a,b)<=200;return String(a.location||'').trim().toLowerCase().replace(/\s+/g,' ')===String(b.location||'').trim().toLowerCase().replace(/\s+/g,' ')}
function assessment(report){const recent=reports.filter(x=>Date.now()-x.date<86400000&&samePlace(x,report)),people=new Set(recent.map(x=>String(x.name||'').trim().toLowerCase()).filter(Boolean)),sameSender=recent.filter(x=>String(x.name||'').trim().toLowerCase()===String(report.name||'').trim().toLowerCase()),medical=/medicinal/i.test(report.type||''),sensitive=(report.nearbyPlaces||[]).length>0;return {urgent:people.size>=3,sensitive,medical,repeatReview:sameSender.length>=3,priority:people.size>=3?'Urgent':(sensitive||medical)?'High':report.priority||'Medium',people:people.size}}
async function findNearbyPlaces(latitude,longitude){const query=`[out:json][timeout:12];(nwr(around:500,${latitude},${longitude})[amenity=hospital];nwr(around:500,${latitude},${longitude})[amenity=clinic];nwr(around:500,${latitude},${longitude})[railway=station];nwr(around:500,${latitude},${longitude})[public_transport=station];);out center tags;`;const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),14000);try{const response=await fetch('https://overpass-api.de/api/interpreter',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body:'data='+encodeURIComponent(query),signal:controller.signal});if(!response.ok)throw new Error('Nearby map search unavailable');const json=await response.json();return (json.elements||[]).map(item=>{const point=item.center||item,tags=item.tags||{},kind=(tags.railway==='station'||tags.public_transport==='station')?'Railway station':'Hospital / clinic';return {name:tags.name||kind,type:kind,latitude:point.lat,longitude:point.lon,distance:Math.round(distanceMeters({latitude,longitude},{latitude:point.lat,longitude:point.lon}))}}).sort((a,b)=>a.distance-b.distance).slice(0,4)}finally{clearTimeout(timer)}}
function artFor(kind){if(kind==='photo')return '';const common='<svg viewBox="0 0 420 210" preserveAspectRatio="xMidYMid slice" aria-hidden="true">';if(kind==='canal')return common+'<rect width="420" height="210" fill="#d9e9dd"/><path d="M0 89 Q125 57 220 91 T420 74V210H0Z" fill="#9fbeae"/><path d="M0 129 Q105 104 210 127 T420 110V210H0Z" fill="#96bcb8"/><path d="M0 177 150 117l67 93H0Zm420 0-160-68-51 101h211Z" fill="#c3d7ac"/><path d="M0 190h420" stroke="#f4eedc" stroke-width="18"/><g fill="#56825e"><circle cx="47" cy="60" r="27"/><circle cx="87" cy="61" r="20"/><circle cx="354" cy="55" r="34"/></g><g fill="#e7d79d"><rect x="162" y="145" width="17" height="9" rx="4" transform="rotate(-13 162 145)"/><rect x="281" y="154" width="22" height="10" rx="4" transform="rotate(20 281 154)"/><rect x="326" y="134" width="14" height="8" rx="4" transform="rotate(-20 326 134)"/></g></svg>';
 if(kind==='street')return common+'<rect width="420" height="210" fill="#e8e8d6"/><rect y="116" width="420" height="94" fill="#b6c59e"/><path d="M0 181 132 118h136l152 92H0Z" fill="#d6c9a8"/><path d="M154 119h112l82 91H74Z" fill="#b9b8a7"/><path d="M0 116h420" stroke="#f4efde" stroke-width="9"/><rect x="22" y="70" width="85" height="49" fill="#e6a981"/><path d="m14 72 51-42 52 42" fill="#ce8362"/><rect x="291" y="70" width="104" height="48" fill="#eacb8e"/><path d="m281 73 61-42 63 42" fill="#b88f55"/><g fill="#6f9c6d"><circle cx="120" cy="94" r="24"/><circle cx="278" cy="93" r="26"/></g><g fill="#96a46a"><path d="M185 157q25-25 47 0-22 26-47 0"/><circle cx="215" cy="157" r="13" fill="#d39e63"/></g></svg>';
 return common+'<rect width="420" height="210" fill="#e4ead9"/><circle cx="335" cy="39" r="25" fill="#efd89c"/><path d="M0 115 101 51l105 64v95H0Z" fill="#e9aa82"/><path d="m88 60 113-69 119 75-12 13L200 18 99 78Z" fill="#ce8163"/><path d="M228 98 307 43l86 57v110H228Z" fill="#e6c783"/><path d="m215 103 92-70 98 70-12 13-86-63-82 63Z" fill="#b88c56"/><path d="M0 177q106-28 202 2t218-6v37H0Z" fill="#b8d39f"/><path d="M0 189q130-24 220 3t200-4" fill="none" stroke="#fff4df" stroke-width="17"/><g fill="#6c9c69"><circle cx="56" cy="114" r="31"/><circle cx="384" cy="118" r="35"/></g><g fill="#d8e8cb"><rect x="35" y="143" width="45" height="49" rx="5"/><path d="M47 138q9-20 18 0" fill="none" stroke="#608761" stroke-width="5"/></g></svg>'}
function statusPill(status){return `<span class="status-pill status-${slug(status)}"><i></i>${escapeHTML(status)}</span>`}
function reportCard(r){const image=r.image?`<img src="${r.image}" alt="Photo submitted with the report" style="width:100%;height:100%;object-fit:cover">`:artFor(r.art||'bins'),a=assessment(r),places=(r.nearbyPlaces||[]).map(p=>`${escapeHTML(p.type)}: ${escapeHTML(p.name)} (${p.distance} m)`).join(' · '),flags=[a.urgent?'Urgent · multiple neighbours reported here':'',a.repeatReview?'Review · repeated reports from same name':'',a.sensitive?'Near a hospital / railway station':'',a.medical?'Safety · medicinal waste':''].filter(Boolean);return `<article class="report-card"><div class="report-image">${image}<span class="image-label">✳ Neighbourhood watch</span><span class="priority-pill priority-${a.priority.toLowerCase()}"><i></i>${escapeHTML(a.priority)} priority</span></div><div class="report-body"><div class="report-topline"><span class="report-type">${escapeHTML(r.type)}</span>${statusPill(r.status)}</div><h3>${escapeHTML(r.title)}</h3><div class="location-line"><span>⌖</span>${escapeHTML(r.location)}</div>${places?`<div class="sensitive-place">⚑ Nearby: ${places}</div>`:''}${flags.length?`<div class="auto-flags">${flags.map(x=>`<span>${escapeHTML(x)}</span>`).join('')}</div>`:''}<p class="report-description">${escapeHTML(r.description)}</p><div class="report-footer"><span>Reported ${timeAgo(r.date)}</span><button class="upvote-button" data-upvote="${r.id}" aria-label="Mark this report as affecting you">♡ &nbsp;${r.upvotes||0} affected</button></div></div></article>`}
function renderCards(){const query=document.querySelector('#search').value.trim().toLowerCase();const filtered=reports.filter(r=>{const matchesFilter=activeFilter==='all'||(activeFilter==='active'&&['Reported','Assigned','In Progress'].includes(r.status))||(activeFilter==='resolved'&&['Resolved','Verified'].includes(r.status));return matchesFilter&&(`${r.location} ${r.title} ${r.type}`).toLowerCase().includes(query)});document.querySelector('#report-grid').innerHTML=filtered.map(reportCard).join('');document.querySelector('#empty-state').hidden=filtered.length>0;document.querySelector('#all-count').textContent=reports.length;document.querySelector('#table-count').textContent=`Showing ${reports.length} report${reports.length===1?'':'s'}`;document.querySelector('#proof-count').textContent=128+reports.length-3}
function renderTable(){const rows=reports.map(r=>{const a=assessment(r),flags=[a.urgent?'URGENT: multiple reports':'',a.repeatReview?'REVIEW: repeat sender':'',a.sensitive?'Near hospital / railway':'',a.medical?'Medicinal waste safety':''].filter(Boolean);return `<tr><td><div class="admin-report-cell"><span class="mini-thumb">${r.image?'▧':'✳'}</span><span>${escapeHTML(r.title)}</span></div></td><td>${escapeHTML(r.location)}${r.latitude!=null?`<a class="map-link" href="https://maps.google.com/?q=${encodeURIComponent(`${r.latitude},${r.longitude}`)}" target="_blank" rel="noopener">⌖ Map</a>`:''}</td><td>${flags.length?flags.map(f=>`<span class="admin-flag ${f.startsWith('URGENT')?'urgent':f.startsWith('REVIEW')?'review':f.startsWith('Medicinal')?'urgent':'sensitive'}">${escapeHTML(f)}</span>`).join(''):'—'}</td><td><select class="status-select" data-assign="${r.id}" aria-label="Assign worker for ${escapeHTML(r.title)}"><option value="">Unassigned</option>${workers.map(w=>`<option value="${w.id}" ${r.assignedTo===w.id?'selected':''}>${w.name}</option>`).join('')}</select></td><td><input class="pay-input" type="number" min="0" step="50" value="${Number(r.payAmount)||0}" data-pay="${r.id}" aria-label="Worker payment for ${escapeHTML(r.title)}"></td><td><button class="payment-toggle ${r.paymentStatus==='Paid'?'paid':''}" data-payment="${r.id}">${r.paymentStatus||'Unpaid'}</button></td><td><select class="status-select" data-status="${r.id}" aria-label="Change status for ${escapeHTML(r.title)}">${statuses.map(s=>`<option ${s===r.status?'selected':''}>${s}</option>`).join('')}</select></td></tr>`}).join('');document.querySelector('#admin-rows').innerHTML=rows;const resolved=reports.filter(r=>['Resolved','Verified'].includes(r.status)).length,pending=reports.length-resolved;document.querySelector('#admin-total').textContent=String(reports.length).padStart(2,'0');document.querySelector('#admin-resolved').textContent=String(resolved).padStart(2,'0');document.querySelector('#admin-pending').textContent=String(pending).padStart(2,'0');document.querySelector('#stat-reports').textContent=String(reports.length).padStart(2,'0');document.querySelector('#stat-resolved').textContent=String(resolved).padStart(2,'0');document.querySelector('#stat-active').textContent=String(pending).padStart(2,'0')}
function render(){renderCards();renderTable();renderWorkerJobs();renderWorkerLocations()}
function showToast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2600)}
const modal=document.querySelector('#report-modal');function openModal(){modal.hidden=false;document.body.style.overflow='hidden';document.querySelector('#report-form').hidden=false;document.querySelector('#success-message').hidden=true;setTimeout(()=>modal.querySelector('input[name="name"]').focus(),50)}function closeModal(){modal.hidden=true;document.body.style.overflow=''}
document.querySelectorAll('[data-open-report]').forEach(b=>b.addEventListener('click',openModal));document.querySelector('.modal-close').addEventListener('click',closeModal);modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden)closeModal()});document.querySelector('#success-done').addEventListener('click',closeModal);
document.querySelector('#report-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,data=new FormData(form),file=data.get('photo');if(form.elements.latitude.value)await nearbyLookupPromise;const addReport=image=>{const location=data.get('location').trim(),type=data.get('type'),description=data.get('description').trim(),title=description.length>52?description.slice(0,49).trimEnd()+'…':description;const report={id:`SS-${String(Date.now()).slice(-6)}`,title,name:data.get('name').trim(),location,type,description,latitude:data.get('latitude')?Number(data.get('latitude')):null,longitude:data.get('longitude')?Number(data.get('longitude')):null,nearbyPlaces:currentNearbyPlaces,priority:/overflow|school|hospital|block.*road|several days|days/i.test(description)?'High':'Medium',status:'Reported',date:Date.now(),upvotes:0,art:'bins',assignedTo:'',payAmount:0,paymentStatus:'Unpaid',...(image?{image}:{})};reports.unshift(report);currentNearbyPlaces=[];saveReports();render();form.reset();document.querySelector('#gps-result').textContent='';form.hidden=true;document.querySelector('#success-message').hidden=false};if(file&&file.size>0){if(file.size>1_500_000){showToast('Please choose an image under 1.5 MB.');return}const reader=new FileReader();reader.onload=()=>addReport(reader.result);reader.readAsDataURL(file)}else addReport(null)});
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');activeFilter=b.dataset.filter;renderCards()}));document.querySelector('#search').addEventListener('input',renderCards);
document.querySelector('#admin-rows').addEventListener('change',e=>{const el=e.target;const report=reports.find(r=>r.id===(el.dataset.status||el.dataset.assign||el.dataset.pay));if(!report)return;if(el.dataset.status){report.status=el.value;showToast(`Status updated to ${report.status}.`)}if(el.dataset.assign!==undefined){report.assignedTo=el.value;if(el.value&&!['In Progress','Resolved','Verified'].includes(report.status))report.status='Assigned';showToast(el.value?'Work assigned to '+workers.find(w=>w.id===el.value).name:'Worker assignment removed.')}if(el.dataset.pay!==undefined){report.payAmount=Math.max(0,Number(el.value)||0);showToast('Worker payment amount saved.')}saveReports();render();renderWorkerJobs()});
document.querySelector('#admin-rows').addEventListener('click',e=>{const button=e.target.closest('[data-payment]');if(!button)return;const report=reports.find(r=>r.id===button.dataset.payment);if(!report)return;report.paymentStatus=report.paymentStatus==='Paid'?'Unpaid':'Paid';saveReports();renderTable();renderWorkerJobs();showToast(`Payment marked ${report.paymentStatus.toLowerCase()}.`)});
document.querySelector('#report-grid').addEventListener('click',e=>{const button=e.target.closest('[data-upvote]');if(!button)return;const report=reports.find(r=>r.id===button.dataset.upvote);if(report){report.upvotes=(report.upvotes||0)+1;saveReports();renderCards();showToast('Thanks for supporting this report.')}});
function setAdminNav(signedIn){const link=document.querySelector('[data-view-link="admin-login"],[data-view-link="admin"]');link.textContent=signedIn?'Admin dashboard':'Admin login';link.href=signedIn?'#admin':'#admin-login';link.dataset.viewLink=signedIn?'admin':'admin-login'}
document.querySelector('#admin-login-form').addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget,id=form.elements.loginId.value.trim(),password=form.elements.password.value;if(id!==ADMIN_LOGIN_ID||password!==ADMIN_PASSWORD){document.querySelector('#login-error').hidden=false;form.elements.password.value='';form.elements.password.focus();return}document.querySelector('#login-error').hidden=true;document.querySelector('#admin-login').hidden=true;document.querySelector('#admin').hidden=false;sessionStorage.setItem('safaisathi-admin-signed-in','yes');setAdminNav(true);document.querySelector('[data-view-link="admin"]').classList.add('active');document.querySelector('#admin').scrollIntoView({behavior:'smooth'});showToast('Welcome to the admin dashboard.')});
document.querySelector('#admin-logout').addEventListener('click',()=>{sessionStorage.removeItem('safaisathi-admin-signed-in');document.querySelector('#admin').hidden=true;document.querySelector('#admin-login').hidden=false;setAdminNav(false);document.querySelector('[data-view-link="admin-login"]').classList.add('active');document.querySelector('#admin-login').scrollIntoView({behavior:'smooth'});showToast('You have signed out.')});
if(sessionStorage.getItem('safaisathi-admin-signed-in')==='yes'){document.querySelector('#admin-login').hidden=true;document.querySelector('#admin').hidden=false;setAdminNav(true)}
function setWorkerNav(signedIn){const link=document.querySelector('[data-view-link="worker-login"],[data-view-link="worker-portal"]');if(!link)return;link.textContent=signedIn?'My jobs':'Worker portal';link.href=signedIn?'#worker-portal':'#worker-login';link.dataset.viewLink=signedIn?'worker-portal':'worker-login'}
function renderWorkerJobs(){const workerId=sessionStorage.getItem('safaisathi-worker');if(!workerId)return;const worker=workers.find(w=>w.id===workerId);if(!worker)return;const assigned=reports.filter(r=>r.assignedTo===workerId);document.querySelector('#worker-name').textContent=`${worker.name} (${worker.id})`;const container=document.querySelector('#worker-jobs');container.innerHTML=assigned.length?assigned.map(r=>{const a=assessment(r),places=(r.nearbyPlaces||[]).map(p=>`${p.type}: ${p.name} · ${p.distance} m`).join(' · ');return `<article class="worker-job"><div class="worker-job-heading"><div><span class="job-id">${escapeHTML(r.id)} · ${escapeHTML(a.priority.toUpperCase())} PRIORITY</span><h3>${escapeHTML(r.title)}</h3></div>${statusPill(r.status)}</div><p class="worker-location">⌖ ${escapeHTML(r.location)} ${r.latitude!=null?`· <a target="_blank" rel="noopener" href="https://maps.google.com/?q=${encodeURIComponent(`${r.latitude},${r.longitude}`)}">Open GPS map ↗</a>`:''}</p>${places?`<div class="sensitive-place">⚑ Nearby: ${escapeHTML(places)}</div>`:''}<p class="worker-description">${escapeHTML(r.description)}</p><div class="worker-job-bottom"><div class="worker-pay"><span>Payment</span><strong>₹${Number(r.payAmount||0).toLocaleString('en-IN')}</strong><small class="${r.paymentStatus==='Paid'?'pay-paid':''}">${escapeHTML(r.paymentStatus||'Unpaid')}</small></div><label class="worker-status-label">Update job status<select class="status-select worker-status" data-worker-status="${r.id}">${['Assigned','In Progress','Resolved'].map(s=>`<option ${r.status===s?'selected':''}>${s}</option>`).join('')}</select></label></div></article>`}).join(''):'<div class="worker-empty"><span>✓</span><h3>No jobs assigned yet</h3><p>New work orders from your admin will show up here.</p></div>'}
function readWorkerLocations(){try{return JSON.parse(localStorage.getItem(WORKER_LOCATIONS_KEY)||'{}')}catch{return {}}}
function renderWorkerLocations(){const locations=readWorkerLocations(),container=document.querySelector('#worker-location-list');if(!container)return;container.innerHTML=workers.map(worker=>{const point=locations[worker.id],live=!!point&&!!point.sharing&&Date.now()-point.updatedAt<60000;return `<div class="worker-location-item"><span class="worker-location-avatar">${escapeHTML(worker.name.charAt(0))}</span><div class="worker-location-info"><strong>${escapeHTML(worker.name)}</strong><span>${point?`${Number(point.latitude).toFixed(5)}, ${Number(point.longitude).toFixed(5)} · ${live?'Sharing live':'Last seen'} ${timeAgo(point.updatedAt)}`:'No location shared yet'}</span></div>${point?`<a class="map-link" target="_blank" rel="noopener" href="https://maps.google.com/?q=${encodeURIComponent(`${point.latitude},${point.longitude}`)}">View map ↗</a>`:''}<i class="location-live-dot ${live?'is-live':''}"></i></div>`}).join('')}
function startWorkerLocationSharing(){const workerId=sessionStorage.getItem('safaisathi-worker'),status=document.querySelector('#worker-location-status');if(!workerId)return;if(!navigator.geolocation){status.textContent='GPS is unavailable in this browser.';return}if(workerWatchId!==null)return;status.textContent='Allow location access to share your live GPS with the admin.';workerWatchId=navigator.geolocation.watchPosition(position=>{const locations=readWorkerLocations();locations[workerId]={latitude:position.coords.latitude,longitude:position.coords.longitude,updatedAt:Date.now(),sharing:true};localStorage.setItem(WORKER_LOCATIONS_KEY,JSON.stringify(locations));status.textContent=`Live location sharing · ${position.coords.latitude.toFixed(5)}, ${position.coords.longitude.toFixed(5)} · updated just now`;document.querySelector('#worker-share-location').hidden=true;document.querySelector('#worker-stop-location').hidden=false;renderWorkerLocations()},error=>{status.textContent=error.code===1?'Location permission denied. Enable it in browser settings to share GPS.':'GPS could not be read. Try again outdoors.';workerWatchId=null},{enableHighAccuracy:true,maximumAge:10000,timeout:20000})}
function stopWorkerLocationSharing(){if(workerWatchId!==null){navigator.geolocation.clearWatch(workerWatchId);workerWatchId=null}const workerId=sessionStorage.getItem('safaisathi-worker');if(workerId){const locations=readWorkerLocations();if(locations[workerId]){locations[workerId].sharing=false;locations[workerId].updatedAt=Date.now();localStorage.setItem(WORKER_LOCATIONS_KEY,JSON.stringify(locations))}}document.querySelector('#worker-share-location').hidden=false;document.querySelector('#worker-stop-location').hidden=true;document.querySelector('#worker-location-status').textContent='Live location sharing is off.';renderWorkerLocations()}
document.querySelector('#worker-login-form').addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget,id=form.elements.workerId.value.trim().toUpperCase(),pin=form.elements.pin.value,worker=workers.find(w=>w.id===id&&w.pin===pin);if(!worker){document.querySelector('#worker-login-error').hidden=false;form.elements.pin.value='';return}sessionStorage.setItem('safaisathi-worker',worker.id);document.querySelector('#worker-login-error').hidden=true;document.querySelector('#worker-login').hidden=true;document.querySelector('#worker-portal').hidden=false;setWorkerNav(true);renderWorkerJobs();document.querySelector('#worker-portal').scrollIntoView({behavior:'smooth'});showToast(`Welcome, ${worker.name}.`)});
document.querySelector('#worker-share-location').addEventListener('click',startWorkerLocationSharing);document.querySelector('#worker-stop-location').addEventListener('click',stopWorkerLocationSharing);
document.querySelector('#worker-logout').addEventListener('click',()=>{stopWorkerLocationSharing();sessionStorage.removeItem('safaisathi-worker');document.querySelector('#worker-portal').hidden=true;document.querySelector('#worker-login').hidden=false;setWorkerNav(false);document.querySelector('#worker-login').scrollIntoView({behavior:'smooth'})});
if(sessionStorage.getItem('safaisathi-worker')){document.querySelector('#worker-login').hidden=true;document.querySelector('#worker-portal').hidden=false;setWorkerNav(true);renderWorkerJobs()}
document.querySelector('#worker-portal').addEventListener('change',e=>{const id=e.target.dataset.workerStatus;if(!id)return;const report=reports.find(r=>r.id===id);if(!report)return;report.status=e.target.value;saveReports();render();showToast(`Job status updated to ${report.status}.`)});
document.querySelector('#get-location').addEventListener('click',()=>{const result=document.querySelector('#gps-result'),submit=document.querySelector('#report-form [type="submit"]');if(!navigator.geolocation){result.textContent='GPS is not available in this browser.';return}result.textContent='Requesting GPS permission…';navigator.geolocation.getCurrentPosition(position=>{const {latitude,longitude}=position.coords,form=document.querySelector('#report-form');form.elements.latitude.value=latitude.toFixed(6);form.elements.longitude.value=longitude.toFixed(6);if(!form.elements.location.value.trim())form.elements.location.value=`GPS ${latitude.toFixed(5)}, ${longitude.toFixed(5)}`;currentNearbyPlaces=[];submit.disabled=true;result.textContent='GPS captured. Checking nearby hospitals and railway stations…';nearbyLookupPromise=findNearbyPlaces(latitude,longitude).then(places=>{currentNearbyPlaces=places;result.textContent=places.length?`GPS captured. Nearby: ${places.map(p=>`${p.name} (${p.distance} m)`).join('; ')}`:'GPS captured. No nearby hospital or railway station found within 500 m.';}).catch(()=>{currentNearbyPlaces=[];result.textContent='GPS captured; nearby-place lookup is unavailable right now.'}).finally(()=>{submit.disabled=false})},error=>{result.textContent=error.code===1?'Location permission denied. You can enter the area manually.':'Could not get location. Try again or enter the area manually.'},{enableHighAccuracy:true,timeout:12000,maximumAge:30000})});
window.addEventListener('storage',e=>{if(e.key===STORAGE_KEY){reports=loadReports();render()}if(e.key===WORKER_LOCATIONS_KEY)renderWorkerLocations()});
renderWorkerLocations();
document.querySelectorAll('[data-view-link]').forEach(link=>link.addEventListener('click',()=>{document.querySelectorAll('[data-view-link]').forEach(x=>x.classList.remove('active'));link.classList.add('active');document.querySelector('.main-nav').classList.remove('open');document.querySelector('.menu-toggle').setAttribute('aria-expanded','false')}));document.querySelector('.menu-toggle').addEventListener('click',e=>{const nav=document.querySelector('.main-nav'),open=nav.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',String(open))});
render();
