const STORAGE_KEY = 'safaisathi-reports-v1';
const statuses = ['Reported', 'Assigned', 'In Progress', 'Resolved', 'Verified'];
const seedReports = [
  {id:'SS-024',title:'Overflowing bins near the park',name:'Riya S.',location:'Green Park, Block C',type:'Household waste',description:'The bins by the park entrance have been overflowing since yesterday evening.',priority:'High',status:'Reported',date:Date.now()-1000*60*60*3,upvotes:12,art:'bins'},
  {id:'SS-023',title:'Plastic waste along the canal',name:'Arjun M.',location:'Riverside Walk, East Gate',type:'Plastic waste',description:'Plastic bottles and wrappers are collecting along the footpath and water edge.',priority:'Medium',status:'In Progress',date:Date.now()-1000*60*60*28,upvotes:8,art:'canal'},
  {id:'SS-022',title:'Food waste left at bus stop',name:'Meera K.',location:'Lake Road Bus Stop',type:'Food waste',description:'A pile of food scraps has been left near the shelter. It is attracting stray animals.',priority:'Low',status:'Resolved',date:Date.now()-1000*60*60*72,upvotes:5,art:'street'}
];
let reports = loadReports();
let activeFilter = 'all';
let toastTimer;
function loadReports(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));return Array.isArray(saved)?saved:seedReports}catch{return seedReports}}
function saveReports(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(reports))}catch{showToast('Storage is full. Try a smaller photo.')}}
function escapeHTML(value=''){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function slug(status){return status==='In Progress'?'progress':status.toLowerCase()}
function formatDate(value){const d=new Date(value);if(Date.now()-d.getTime()<86400000)return 'Today, '+d.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});return d.toLocaleDateString([],{day:'numeric',month:'short'})}
function timeAgo(value){const hours=Math.max(0,Math.floor((Date.now()-value)/3600000));if(hours<1)return 'Just now';if(hours<24)return `${hours} hour${hours===1?'':'s'} ago`;const days=Math.floor(hours/24);return `${days} day${days===1?'':'s'} ago`}
function artFor(kind){if(kind==='photo')return '';const common='<svg viewBox="0 0 420 210" preserveAspectRatio="xMidYMid slice" aria-hidden="true">';if(kind==='canal')return common+'<rect width="420" height="210" fill="#d9e9dd"/><path d="M0 89 Q125 57 220 91 T420 74V210H0Z" fill="#9fbeae"/><path d="M0 129 Q105 104 210 127 T420 110V210H0Z" fill="#96bcb8"/><path d="M0 177 150 117l67 93H0Zm420 0-160-68-51 101h211Z" fill="#c3d7ac"/><path d="M0 190h420" stroke="#f4eedc" stroke-width="18"/><g fill="#56825e"><circle cx="47" cy="60" r="27"/><circle cx="87" cy="61" r="20"/><circle cx="354" cy="55" r="34"/></g><g fill="#e7d79d"><rect x="162" y="145" width="17" height="9" rx="4" transform="rotate(-13 162 145)"/><rect x="281" y="154" width="22" height="10" rx="4" transform="rotate(20 281 154)"/><rect x="326" y="134" width="14" height="8" rx="4" transform="rotate(-20 326 134)"/></g></svg>';
 if(kind==='street')return common+'<rect width="420" height="210" fill="#e8e8d6"/><rect y="116" width="420" height="94" fill="#b6c59e"/><path d="M0 181 132 118h136l152 92H0Z" fill="#d6c9a8"/><path d="M154 119h112l82 91H74Z" fill="#b9b8a7"/><path d="M0 116h420" stroke="#f4efde" stroke-width="9"/><rect x="22" y="70" width="85" height="49" fill="#e6a981"/><path d="m14 72 51-42 52 42" fill="#ce8362"/><rect x="291" y="70" width="104" height="48" fill="#eacb8e"/><path d="m281 73 61-42 63 42" fill="#b88f55"/><g fill="#6f9c6d"><circle cx="120" cy="94" r="24"/><circle cx="278" cy="93" r="26"/></g><g fill="#96a46a"><path d="M185 157q25-25 47 0-22 26-47 0"/><circle cx="215" cy="157" r="13" fill="#d39e63"/></g></svg>';
 return common+'<rect width="420" height="210" fill="#e4ead9"/><circle cx="335" cy="39" r="25" fill="#efd89c"/><path d="M0 115 101 51l105 64v95H0Z" fill="#e9aa82"/><path d="m88 60 113-69 119 75-12 13L200 18 99 78Z" fill="#ce8163"/><path d="M228 98 307 43l86 57v110H228Z" fill="#e6c783"/><path d="m215 103 92-70 98 70-12 13-86-63-82 63Z" fill="#b88c56"/><path d="M0 177q106-28 202 2t218-6v37H0Z" fill="#b8d39f"/><path d="M0 189q130-24 220 3t200-4" fill="none" stroke="#fff4df" stroke-width="17"/><g fill="#6c9c69"><circle cx="56" cy="114" r="31"/><circle cx="384" cy="118" r="35"/></g><g fill="#d8e8cb"><rect x="35" y="143" width="45" height="49" rx="5"/><path d="M47 138q9-20 18 0" fill="none" stroke="#608761" stroke-width="5"/></g></svg>'}
function statusPill(status){return `<span class="status-pill status-${slug(status)}"><i></i>${escapeHTML(status)}</span>`}
function reportCard(r){const image=r.image?`<img src="${r.image}" alt="Photo submitted with the report" style="width:100%;height:100%;object-fit:cover">`:artFor(r.art||'bins');return `<article class="report-card"><div class="report-image">${image}<span class="image-label">✳ Neighbourhood watch</span><span class="priority-pill priority-${r.priority.toLowerCase()}"><i></i>${escapeHTML(r.priority)} priority</span></div><div class="report-body"><div class="report-topline"><span class="report-type">${escapeHTML(r.type)}</span>${statusPill(r.status)}</div><h3>${escapeHTML(r.title)}</h3><div class="location-line"><span>⌖</span>${escapeHTML(r.location)}</div><p class="report-description">${escapeHTML(r.description)}</p><div class="report-footer"><span>Reported ${timeAgo(r.date)}</span><button class="upvote-button" data-upvote="${r.id}" aria-label="Mark this report as affecting you">♡ &nbsp;${r.upvotes||0} affected</button></div></div></article>`}
function renderCards(){const query=document.querySelector('#search').value.trim().toLowerCase();const filtered=reports.filter(r=>{const matchesFilter=activeFilter==='all'||(activeFilter==='active'&&['Reported','Assigned','In Progress'].includes(r.status))||(activeFilter==='resolved'&&['Resolved','Verified'].includes(r.status));return matchesFilter&&(`${r.location} ${r.title} ${r.type}`).toLowerCase().includes(query)});document.querySelector('#report-grid').innerHTML=filtered.map(reportCard).join('');document.querySelector('#empty-state').hidden=filtered.length>0;document.querySelector('#all-count').textContent=reports.length;document.querySelector('#table-count').textContent=`Showing ${reports.length} report${reports.length===1?'':'s'}`;document.querySelector('#proof-count').textContent=128+reports.length-3}
function renderTable(){const rows=reports.map(r=>`<tr><td><div class="admin-report-cell"><span class="mini-thumb">${r.image?'▧':'✳'}</span><span>${escapeHTML(r.title)}</span></div></td><td>${escapeHTML(r.location)}</td><td>${escapeHTML(r.type)}</td><td><span class="priority-text ${r.priority.toLowerCase()}">${escapeHTML(r.priority.toUpperCase())}</span></td><td><select class="status-select" data-status="${r.id}" aria-label="Change status for ${escapeHTML(r.title)}">${statuses.map(s=>`<option ${s===r.status?'selected':''}>${s}</option>`).join('')}</select></td><td>${formatDate(r.date)}</td></tr>`).join('');document.querySelector('#admin-rows').innerHTML=rows;const resolved=reports.filter(r=>['Resolved','Verified'].includes(r.status)).length,pending=reports.length-resolved;document.querySelector('#admin-total').textContent=String(reports.length).padStart(2,'0');document.querySelector('#admin-resolved').textContent=String(resolved).padStart(2,'0');document.querySelector('#admin-pending').textContent=String(pending).padStart(2,'0');document.querySelector('#stat-reports').textContent=String(reports.length).padStart(2,'0');document.querySelector('#stat-resolved').textContent=String(resolved).padStart(2,'0');document.querySelector('#stat-active').textContent=String(pending).padStart(2,'0')}
function render(){renderCards();renderTable()}
function showToast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2600)}
const modal=document.querySelector('#report-modal');function openModal(){modal.hidden=false;document.body.style.overflow='hidden';document.querySelector('#report-form').hidden=false;document.querySelector('#success-message').hidden=true;setTimeout(()=>modal.querySelector('input[name="name"]').focus(),50)}function closeModal(){modal.hidden=true;document.body.style.overflow=''}
document.querySelectorAll('[data-open-report]').forEach(b=>b.addEventListener('click',openModal));document.querySelector('.modal-close').addEventListener('click',closeModal);modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden)closeModal()});document.querySelector('#success-done').addEventListener('click',closeModal);
document.querySelector('#report-form').addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget,data=new FormData(form),file=data.get('photo');const addReport=image=>{const location=data.get('location').trim(),type=data.get('type'),description=data.get('description').trim(),title=description.length>52?description.slice(0,49).trimEnd()+'…':description;const report={id:`SS-${String(Date.now()).slice(-6)}`,title, name:data.get('name').trim(),location,type,description,priority:/overflow|school|hospital|block.*road|several days|days/i.test(description)?'High':'Medium',status:'Reported',date:Date.now(),upvotes:0,art:'bins',...(image?{image}:{})};reports.unshift(report);saveReports();render();form.reset();form.hidden=true;document.querySelector('#success-message').hidden=false};if(file&&file.size>0){if(file.size>1_500_000){showToast('Please choose an image under 1.5 MB.');return}const reader=new FileReader();reader.onload=()=>addReport(reader.result);reader.readAsDataURL(file)}else addReport(null)});
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');activeFilter=b.dataset.filter;renderCards()}));document.querySelector('#search').addEventListener('input',renderCards);
document.querySelector('#admin-rows').addEventListener('change',e=>{const id=e.target.dataset.status;if(!id)return;const report=reports.find(r=>r.id===id);if(!report)return;report.status=e.target.value;saveReports();render();showToast(`Status updated to ${report.status}.`)});
document.querySelector('#report-grid').addEventListener('click',e=>{const button=e.target.closest('[data-upvote]');if(!button)return;const report=reports.find(r=>r.id===button.dataset.upvote);if(report){report.upvotes=(report.upvotes||0)+1;saveReports();renderCards();showToast('Thanks for supporting this report.')}});
document.querySelectorAll('[data-view-link]').forEach(link=>link.addEventListener('click',()=>{document.querySelectorAll('[data-view-link]').forEach(x=>x.classList.remove('active'));link.classList.add('active');document.querySelector('.main-nav').classList.remove('open');document.querySelector('.menu-toggle').setAttribute('aria-expanded','false')}));document.querySelector('.menu-toggle').addEventListener('click',e=>{const nav=document.querySelector('.main-nav'),open=nav.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',String(open))});
render();
